
-- ERSTELLI Supabase schema
create extension if not exists pgcrypto;

create table if not exists public.project_requests (
  id uuid primary key default gen_random_uuid(),
  request_id text unique not null,
  name text not null,
  company text,
  email text not null,
  phone text,
  configuration text not null,
  message text,
  quoted_price numeric,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists public.project_files (
  id uuid primary key default gen_random_uuid(),
  request_id text not null references public.project_requests(request_id) on delete cascade,
  original_name text not null,
  storage_path text not null,
  mime_type text,
  size_bytes bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  request_id text unique references public.project_requests(request_id),
  invoice_number text,
  final_price numeric,
  status text not null default 'accepted',
  review_token text unique default encode(gen_random_bytes(18),'hex'),
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete cascade,
  display_name text,
  rating int not null check (rating between 1 and 5),
  text text not null check (char_length(text) between 3 and 1200),
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.project_requests enable row level security;
alter table public.project_files enable row level security;
alter table public.orders enable row level security;
alter table public.reviews enable row level security;

-- No direct anonymous table access. Edge functions use the service-role key.
-- Storage bucket for incoming customer files:
insert into storage.buckets (id,name,public)
values ('project-files','project-files',false)
on conflict (id) do nothing;


-- Datensparsame, eigene Reichweitenmessung ohne Cookies/LocalStorage.
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  session_id text not null,
  page text not null default '/',
  section text,
  element text,
  value text,
  source text,
  medium text,
  campaign text,
  device_group text,
  created_at timestamptz not null default now()
);
create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_name_created_idx on public.analytics_events(event_name,created_at desc);
alter table public.analytics_events enable row level security;
-- Kein direkter anonymer Tabellenzugriff; Schreib-/Lesezugriff erfolgt nur über Edge Functions.
